2025-04-29 12:10:37,421 - print_task - INFO - GET /task/task_id called - task_id=11 by user_id=1
2025-04-29 12:10:37,455 - print_task - INFO - Returning task details for task_id=11
2025-04-29 12:12:00,875 - print_task - INFO - GET /task/task_id called - task_id=15 by user_id=1
2025-04-29 12:12:00,884 - print_task - INFO - Returning task details for task_id=15
2025-04-29 12:12:15,667 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:12:15,679 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:16:50,098 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:16:50,117 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:28:13,189 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:28:13,189 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:29:17,982 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:29:18,034 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:30:05,165 - print_task - INFO - GET /task/task_id called - task_id=11 by user_id=1
2025-04-29 12:30:05,194 - print_task - INFO - Returning task details for task_id=11
2025-04-29 12:30:17,308 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:30:17,342 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:32:15,606 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:32:15,640 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:32:15,640 - print_task - ERROR - Error retrieving task details for task_id=14: name 'mark_as_complete' is not defined
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 349, in task_details
    "mark_as_complete": mark_as_complete,
                        ^^^^^^^^^^^^^^^^
NameError: name 'mark_as_complete' is not defined
2025-04-29 12:32:23,337 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:32:23,361 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:32:23,361 - print_task - ERROR - Error retrieving task details for task_id=14: name 'mark_as_complete' is not defined
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 349, in task_details
    "parent_task_chain": parent_task_chain
                        ^^^^^^^^^^^^^^^^
NameError: name 'mark_as_complete' is not defined
2025-04-29 12:32:27,342 - print_task - INFO - GET /task/task_id called - task_id=14 by user_id=1
2025-04-29 12:32:27,367 - print_task - INFO - Returning task details for task_id=14
2025-04-29 12:32:38,123 - print_task - INFO - GET /task/task_id called - task_id=11 by user_id=1
2025-04-29 12:32:38,130 - print_task - INFO - Returning task details for task_id=11
2025-04-29 12:32:52,357 - print_task - INFO - GET /task/task_id called - task_id=15 by user_id=1
2025-04-29 12:32:52,380 - print_task - INFO - Returning task details for task_id=15
2025-05-02 09:32:01,494 - print_task - INFO - GET /task/task_id called - task_id=1 by user_id=1
2025-05-02 09:32:01,543 - print_task - INFO - Returning task details for task_id=1
2025-05-02 09:32:14,671 - print_task - INFO - GET /task/task_id called - task_id=2 by user_id=1
2025-05-02 09:32:14,688 - print_task - INFO - Returning task details for task_id=2
2025-05-02 09:33:42,364 - print_task - INFO - GET /task/task_id called - task_id=5 by user_id=1
2025-05-02 09:33:42,383 - print_task - ERROR - Error retrieving task details for task_id=5: object of type 'bool' has no len()
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 328, in task_details
    get_parent_chain(task.parent_task_id)
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 306, in get_parent_chain
    last_review = True if len(is_parent) == 0 else False
                      ^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()
2025-05-02 09:34:12,072 - print_task - INFO - GET /task/task_id called - task_id=5 by user_id=1
2025-05-02 09:34:12,097 - print_task - INFO - Returning task details for task_id=5
2025-05-02 09:35:01,402 - print_task - INFO - GET /task/task_id called - task_id=5 by user_id=1
2025-05-02 09:35:01,443 - print_task - INFO - Returning task details for task_id=5
2025-05-02 09:37:24,033 - print_task - INFO - GET /task/task_id called - task_id=5 by user_id=1
2025-05-02 09:37:24,063 - print_task - INFO - Returning task details for task_id=5
2025-05-02 09:41:42,874 - print_task - INFO - GET /task/task_id called - task_id=5 by user_id=1
2025-05-02 09:41:42,908 - print_task - INFO - Returning task details for task_id=5
2025-05-02 10:51:07,056 - print_task - INFO - GET /task/task_id called - task_id=6 by user_id=1
2025-05-02 10:51:07,114 - print_task - INFO - Returning task details for task_id=6
2025-05-02 10:51:47,838 - print_task - INFO - GET /task/task_id called - task_id=6 by user_id=1
2025-05-02 10:51:47,890 - print_task - INFO - Returning task details for task_id=6
2025-05-02 10:51:55,227 - print_task - INFO - GET /task/task_id called - task_id=7 by user_id=1
2025-05-02 10:51:55,255 - print_task - INFO - Returning task details for task_id=7
2025-05-02 10:56:10,246 - print_task - INFO - GET /task/task_id called - task_id=7 by user_id=1
2025-05-02 10:56:10,268 - print_task - INFO - Returning task details for task_id=7
2025-05-02 10:57:11,354 - print_task - INFO - GET /task/task_id called - task_id=7 by user_id=1
2025-05-02 10:57:11,393 - print_task - INFO - Returning task details for task_id=7
2025-05-02 10:57:18,562 - print_task - INFO - GET /task/task_id called - task_id=6 by user_id=1
2025-05-02 10:57:18,596 - print_task - INFO - Returning task details for task_id=6
2025-05-02 10:57:26,912 - print_task - INFO - GET /task/task_id called - task_id=4 by user_id=1
2025-05-02 10:57:26,936 - print_task - ERROR - Error retrieving task details for task_id=4: list index out of range
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 328, in task_details
    first_task = parent_task_chain[0]
                 ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-05-02 10:57:44,800 - print_task - INFO - GET /task/task_id called - task_id=4 by user_id=1
2025-05-02 10:57:44,807 - print_task - ERROR - Error retrieving task details for task_id=4: list index out of range
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 328, in task_details
    if parent_task_chain:
                 ^^^^^^^^^
IndexError: list index out of range
2025-05-02 10:57:49,567 - print_task - INFO - GET /task/task_id called - task_id=4 by user_id=1
2025-05-02 10:57:49,576 - print_task - INFO - Returning task details for task_id=4
