Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 349, in task_details
    "mark_as_complete": mark_as_complete,
                        ^^^^^^^^^^^^^^^^
NameError: name 'mark_as_complete' is not defined
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 349, in task_details
    "parent_task_chain": parent_task_chain
                        ^^^^^^^^^^^^^^^^
NameError: name 'mark_as_complete' is not defined
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 328, in task_details
    get_parent_chain(task.parent_task_id)
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 306, in get_parent_chain
    last_review = True if len(is_parent) == 0 else False
                      ^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 328, in task_details
    first_task = parent_task_chain[0]
                 ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "D:\Task Management System Final code\Tasks\Print_Task.py", line 328, in task_details
    if parent_task_chain:
                 ^^^^^^^^^
IndexError: list index out of range
2025-05-08 16:19:26,309 - print_task - INFO - GET /task/task_id called - task_id=1 by user_id=5
2025-05-08 16:19:26,401 - print_task - INFO - Returning task details for task_id=1
